version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: digital-vault-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: digital_vault
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - digital-vault-network

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: digital-vault-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    volumes:
      - minio_data:/data
    networks:
      - digital-vault-network

  # MinIO Client (for bucket creation)
  minio-client:
    image: minio/mc:latest
    container_name: digital-vault-minio-client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/digital-vault-files --ignore-existing;
      /usr/bin/mc policy set public myminio/digital-vault-files;
      exit 0;
      "
    networks:
      - digital-vault-network

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local

networks:
  digital-vault-network:
    driver: bridge
